apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notepad-argocd-app
  namespace: argocd-demo
spec:
  project: default

  source:
    repoURL: https://github.com/Pratibha2411/argocd-app
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=false

    automated:
      selfHeal: false
      prune: false
