apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-webhook-config-reader-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argo-cd
roleRef:
  kind: ClusterRole
  name: argocd-webhook-config-reader
  apiGroup: rbac.authorization.k8s.io
